// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Account struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Balance    float64 `json:"balance"`
	CustomerID string  `json:"customerId"`
}

type AccountInput struct {
	Name       string `json:"name"`
	CustomerID string `json:"customerID"`
}

type CustomerInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Dob       string `json:"dob"`
}

type Parties struct {
	FromAccount string `json:"fromAccount"`
	ToAccount   string `json:"toAccount"`
}

type Transaction struct {
	Amount      float64 `json:"amount"`
	Description *string `json:"description"`
}
